local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.amazon.access_key_id %>
  secret_access_key: <%= Rails.application.credentials.amazon.secret_access_key %>
  region: "eu-west-3"
  bucket: "arn:aws:s3:::solio-florence-content"
